config/routes.rb
Rails.application.routes.draw do
  resources:tweets
  root 'tweets#index'
  delete '/tweets/:id', to:'tweets#destroy'
  get '/tweets/:id', to:'tweets#show'
  get '/tweets/:id/edit', to:'tweets#edit'
  patch '/tweets/:id', to:'tweets#update'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :message, presence:true
    validates :message, length:{ maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  def new
    @tweet = Tweet.new
  end
  def create
    tweet = Tweet.new
    @tweet = Tweet.new(message: params[:tweet][:message], tdate: Time.current)
    if @tweet.save
      redirect_to '/'
    else
      render 'new'
    end
  end
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to '/'
  end
  def show
    @tweet = Tweet.find(params[:id])
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    tweet = Tweet.find(params[:id])
    tweet.update(message: params[:tweet][:message])
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="header">
      <%= render "header" %>
    </div>
    <div id="sidebar">
      <%= render "sidebar" %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer">
      <%= render "footer" %>
    </div>
  </div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= tw.label :message, '呟き内容:' %><br/>
<%= tw.text_field :message %><br/>
<h1><%= tw.submit '更新' %></h1>

app/views/tweets/edit.html.erb
<%= form_for @tweet,message: {action: :update} do |tw| %>

<%= render "form", tw: tw %>

<% end %>

app/views/tweets/index.html.erb
<h2 id="siteTitle">TWapp</h2>

<% @tweets.each do |tw| %>
  <%= tw.message %>
  
  <% d = Time.current - tw.tdate %>
  <% t = d /60 %>
  
  --<%= t.to_i %>分前
  </form>
  <%= link_to '削除', tweet_path(tw) ,method: :delete %>
  <%= link_to '表示', tweet_path(tw) %>
  <%= link_to '編集', edit_tweet_path(tw) %><br/>
<% end %>

<h1><%= link_to '新しく呟く',  new_tweet_path %></h1>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<ul>
  <% @tweet.errors.full_messages.each do |ermsg| %>
  <li><h2><%= ermsg %></h2></li>
  <% end %>
</ul>
<% end %>

<%= form_for @tweet, message: {action: :create} do |tw| %>

<%= render "form", tw: tw %>

<% end %>

app/views/tweets/show.html.erb
<p>
    <strong>つぶやき</strong><br/>
    <%= @tweet.message %>
    --<%= @tweet.tdate %>
</p>
<%= link_to '戻る', '/' %>